let bobStats = new Stats(5,5,5,5,5);
let Bob = new Player("Bob", bobStats);
let tinaStats = new Stats(5,5,5,5,5);
let Tina = new Player("Tina", tinaStats);
let louiseStats = new Stats(5,5,5,5,5);
let Louise = new Player("Louise", louiseStats);
let lindaStats = new Stats(5,5,5,5,5);
let Linda = new Player("Linda", lindaStats);
let geneStats = new Stats(5,5,5,5,5);
let Gene = new Player("Gene", geneStats);
let selectedPlayer;
let glasses = new Item("Butt detecting glasses", 10, 10, "No butt is safe.", 100);
let tongs = new Item("Tongs of woe", 10, 10, "When grasped by these sacred tongs, there is no escape...", 100);
let bunnyHat = new Item("Bunny Ears", 10, 10, "Fills the wearer with the confidence to push on.", 100);
let spatula = new Item("The Dragon Slayer Spatula", 10, 10, "Glows with blue fire", 100);
let keyboard = new Item("Casio SK5", 10, 10, "This keyboard's beautiful fart sounds will soothe even the most horrible wounds.", 100);
